language: ruby
cache:
  - bundler
install:
  - bundle install
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

addons:
  artifacts: true

deploy:
	skip_cleanup: true
  
script:
  - 'bundle exec rake default'

notifications:
  email:
    recipients:
      - mattjones@yieldbot.com
    on_success: change
    on_failure: always
